
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook notebook1;
	private global::PArticulo.ListArticuloView listarticuloview1;
	private global::Gtk.Label label1;
	private global::PArticulo.ListCategoriaView listcategoriaview1;
	private global::Gtk.Label label3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.listarticuloview1 = new global::PArticulo.ListArticuloView ();
		this.listarticuloview1.Events = ((global::Gdk.EventMask)(256));
		this.listarticuloview1.Name = "listarticuloview1";
		this.notebook1.Add (this.listarticuloview1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Articulos");
		this.notebook1.SetTabLabel (this.listarticuloview1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.listcategoriaview1 = new global::PArticulo.ListCategoriaView ();
		this.listcategoriaview1.Events = ((global::Gdk.EventMask)(256));
		this.listcategoriaview1.Name = "listcategoriaview1";
		this.notebook1.Add (this.listcategoriaview1);
		global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.listcategoriaview1]));
		w2.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoria");
		this.notebook1.SetTabLabel (this.listcategoriaview1, this.label3);
		this.label3.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w3.Position = 0;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 552;
		this.DefaultHeight = 466;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
