
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class ListCategoriaView
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action newAction;
		private global::Gtk.Action editAction1;
		private global::Gtk.Action deleteAction1;
		private global::Gtk.Action refreshAction;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Toolbar toolbar2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeviewCat;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PArticulo.ListCategoriaView
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
			w2.Add (this.newAction, null);
			this.editAction1 = new global::Gtk.Action ("editAction1", null, null, "gtk-edit");
			w2.Add (this.editAction1, null);
			this.deleteAction1 = new global::Gtk.Action ("deleteAction1", null, null, "gtk-delete");
			w2.Add (this.deleteAction1, null);
			this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
			w2.Add (this.refreshAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "PArticulo.ListCategoriaView";
			// Container child PArticulo.ListCategoriaView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='newAction' action='newAction'/><toolitem name='editAction1' action='editAction1'/><toolitem name='deleteAction1' action='deleteAction1'/><toolitem name='refreshAction' action='refreshAction'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.vbox2.Add (this.toolbar2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewCat = new global::Gtk.TreeView ();
			this.treeviewCat.CanFocus = true;
			this.treeviewCat.Name = "treeviewCat";
			this.GtkScrolledWindow.Add (this.treeviewCat);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w5.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
			this.editAction1.Activated += new global::System.EventHandler (this.OnEditActionCategoriaActivated);
			this.deleteAction1.Activated += new global::System.EventHandler (this.OnDeleteActionCategoriaActivated);
			this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionCategoriaActivated);
		}
	}
}
